### ISSUE TITLE
Help with the target location of the project

### ISSUE THREAD

**Issue by comp-17** [grebtsew/FloorplanToBlender3d#18]
Hi there!

I am trying to run the repository and after all the steps mentioned in the document, 
1. I am unable to see any files, or the project created at the below path that appeared after running the project.

------
Creates blender project
Project created at: /home/floorplan_to_blender/Target/floorplan2.blend

2. Where exactly should the blender software be installed. Is it in the Linux /usr/local/blender/blender or a location on windows? 
The demo shows windows but when I give my windows path, it says File not found.

Kindly help me with the issues.

**Comment by grebtsew** [comment]
Hello @comp-17,

Thanks for testing the project and submitting an issue! I agree that the documentation is somewhat lacking and dated.

1.  Okey, I will need some more information in order to answer. Which OS are you running the code on? Are you running locally or using the docker container? 

2. With the latest update the implementation automatically detects the install path of blender, which hopefully still works. If that fails for some reason you can change the installation path manually in the`/Configs/system.ini` file. This config file is created if it doesn't already exist.


Cheers,
@grebtsew

**Comment by comp-17** [comment]
Hello,
I am using Windows 10 Home, build 19044.1766
I am using the docker container to run the code.

Kindly help me out as this helps me with my research project immensely.

Thank you

**Comment by grebtsew** [comment]
Okey. If you are using the docker-compose (i.e. `docker-compose run ftb`) file the ` /home/floorplan_to_blender/Target/` folder in the container is shared/volumed to the `Target` folder of your local filesystem. Meaning a new folder will be created called `Target` where the `.blend` files will be stored.

Note that the `Images` folder also is shared with the docker container in order to add custom images.

An alternative is of course to instead use `docker run` and manually set volumes or use the `scp` command to copy the files from the container. 

The docker container contains a version of blender, so you won't need to install blender in order to run the code through docker. But in order to view the resulting `.blend` files blender is also needed locally.

Cheers,
@grebtsew

**Comment by grebtsew** [comment]
You need to be in the project folder when running `docker-compose run ftb`. If it still doesn't find the configuration file, try using `-f ` flag to specify path.

I'm a bit unsure why `docker run grebtsew/floorplan-to-blender:latest bash` doesn't work. I will try that tomorrow.

**Comment by grebtsew** [comment]
As i mentioned, when using docker the implementation will work in the docker container environment. So the blender file will be created at `/home/floorplan_to_blender/Target/floorplan2.blend` in the container. To access it you can either use a volume (shared folder between your local filesystem and the container, try the docker-compose for instance) or via scp while the container is still running (change entrypoint to make sure the container don't close when done executing the script).

Cheers,
@grebtsew

**Comment by comp-17** [comment]
Hi, I tried the methods you proposed but couldn't get the desired result.
It would be a great help if you could take out some time to remote share
and look into my progress so that you can help me out with the issue if
possible. Kindly let me know.

Thank you so much in advance!

**Comment by grebtsew** [comment]
Hi,

I would prefer if we can solve the issue without a scheduled meeting.

Have you tried installing and running the program locally instead of using docker? Cloning repo, installing python packages and then run the main.py file.

What's the result if you run `docker-compose run ftb` in the project folder?

Cheers,
@grebtsew

**Comment by comp-17** [comment]
Hi,

No problem, I appreciate your assistance!

>>docker-compose run ftb
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml,
compose.yml, compose.yaml

This is the error I am getting.

**Comment by grebtsew** [comment]
Hi again,

Sorry for the late reply.

1.In which directory are you when running the docker-compose command? Are you in the project directory?

2.Have you tried just installing everything locally instead? I.e. install blender, python packages and just run the main.py file?

Cheers,
@grebtsew

**Comment by comp-17** [comment]
Hi, no problem. Thanks for getting back on this issue.
1. I am trying to build and run separately from the project folder.
2. I haven't tried to run locally as my machine doesn't support it.

I believe the issue to be some paths getting modified on my machine. I will
format everything and check if docker-compose - build and run together
works for me.

**Comment by grebtsew** [comment]
1. If you are not in the same folder as the docker-compose.yml file when running the docker-compose command you will have to link to the folder. For instance to run from the parent folder, `docker-compose -f ./FloorplanToBlender3d/docker-compose.yml run ftb`.

2.  Okey.

Cheers,
@grebtsew

**Comment by grebtsew** [comment]
Hi again,

What is the status of this issue?

Cheers,
@grebtsew

**Comment by comp-17** [comment]
Hello there, 

I just got to experiment around the project yesterday and it was working fine. I could see the generated 3D model file in the target location only when I use the docker compose command (build and run at the same time). Otherwise, I don't see. blend files created in the directory. For time being my purpose is served and will explore if necessary.

Thank you for the support you provided and for this amazing project as well.

**Comment by grebtsew** [comment]
Okey thats great to hear! I will then close this issue for now.

Cheers,
@grebtsew

**Comment by comp-17** [comment]
Yeah, thank you so much for all the help!
