### ISSUE TITLE
Gates and Windows!

### ISSUE THREAD

**Issue by khangee12** [grebtsew/FloorplanToBlender3d#3]
Hi! So i checkout all your code and i'm very impress with your intelligence, you are pure gold.
i execute your code and got blender file but only with walls 3D model. how can i generate windows and gates too?

Thanks alot for your contribution

**Comment by grebtsew** [comment]
Hi @khangee12 !

Thanks for testing my code.

In an early version of the implementation I used a function called find_details() to detect windows and gates/doors. However it is currently unused due to: 
1. didn't find differences between windows and doors . 
2. could be unaccurate on floorplans with many small rooms and passages. 

The code is still there, just not used at this time.

I do have plans to update several features including this one in this project, however I am currenly involved in other projects with higher priority right now so I can't specify when I will have time complete them.

I will keep this issue open and make sure to let you know when I've fixed a better window/gate/door detection!

Cheers,
@grebtsew

**Comment by khangee12** [comment]
Hi Greebstsew
Hope you are fine.

So i want to generate a OpenSCAD(3d modeling software) file as an output  can you guide me where can edit this code. and can i able to do this?

**Comment by grebtsew** [comment]
Hi @khangee12 !

I have not done this myself but it should be quite easy. You have two alternatives:
1. Run my script. Open the generated .blender-file and export the project as a .scad-file. You should be able to google how to do that easily.
2. Edit the FloorplanToBlender3d/Blender/floorplan_to_3dObject_in_blender.py code by adding a export path, it should be something like bpy.ops.export_scene.obj(filepath=output_path). 

When I googled, I found several tutorials, one example:
https://mathgrrl.com/hacktastic/2015/10/beefy-trophy-baking-meshes-into-openscad-from-blender/

Hope it helps!

Cheers,
@grebtsew

**Comment by khangee12** [comment]
Thanks for your reply men,
but i found a way to do this. BTW Thanks again.

Now i'm working on the Doors and Windows detection.

Regards

**Comment by grebtsew** [comment]
Cool! Please let me know if you succeed!

Cheers!

**Comment by saraalyy** [comment]
did you manage to show the windows in the blender file?? @khangee12

**Comment by khangee12** [comment]
@saraalyy  unfortunately not!

**Comment by grebtsew** [comment]
Hi!

Today I updated the main/master branch with Window and Doors detections.
They can still be inaccurate, I recommend try changing some constants in const and changing door models or changing input image size to alter results. 

I will therefore close this issue now. Feel free to open new issues.

Cheers,
@grebtsew
