### ISSUE TITLE
Write image file bug in create_file

### ISSUE THREAD

**Issue by Arc-Jung** [grebtsew/FloorplanToBlender3d#38]
![스크린샷 2024-10-02 110418](https://github.com/user-attachments/assets/9fa77fd7-8604-44af-9d6a-a87bef7254c5)

When executing create_file, I added a code to remove the string value "------WebKitFormBoundary" and a code to check it.
I wonder if this bug is caused by a mistake in my frontend request, or if other people may experience the same error. Please leave a comment.

```python
def create_file(ref, id, iformat, file):
    """Write incoming data to file"""
    # Extract the actual image data from the form data
    boundary = b'------WebKitFormBoundary'
    parts = file.split(boundary)
    for part in parts:
        if b'Content-Disposition: form-data; name="data"; filename=' in part:
            # Find the start of the actual image data
            image_data_start = part.find(b'\r\n\r\n') + 4
            image_data = part[image_data_start:]
            break
    else:
        raise ValueError("Image data not found in the form data")

    file_path = ref.shared.parentPath + "/" + ref.shared.imagesPath + "/" + id + iformat
    with open(file_path, "wb") as f:
        f.write(image_data)
```

**Comment by grebtsew** [comment]
Hi @Arc-Jung,

From what I can see, when i run the server tests on my computer, the PUT file test is still passing. So I'm guessing the problem comes from your frontend requests.

The test i refer  to is `./Server/test/test_client.py`. Specifically this part:
![bild](https://github.com/user-attachments/assets/cf7d959e-bd5c-44cb-9b00-44cd7187f4f9)

 The server uses some unconventional RMI api, which unfortunately makes it cumbersome to use.
 
 Cheers,
 @grebtsew

**Comment by Arc-Jung** [comment]
@grebtsew 
Thank you for your answer.
It may not be a problem in the test code, but it may cause an error when developing on the frontend.
If anyone who has the same issue as me sees this issue, please refer to the code above.
