### ISSUE TITLE
Pivot Point not at the center

### ISSUE THREAD

**Issue by shaddeykatri** [grebtsew/FloorplanToBlender3d#4]
Hi I am really thankful to you for this repo as this was exactly what i needed however there is an issue when i try to use it in blender the project that is created has some really offset pivot points for its whole floor plan and its individual components. Please suggest some sources so that I can try to fix that, or if you have any idea please help me out.

**Comment by grebtsew** [comment]
Hello @shaddeykatri!

Thank you for using this implementation!

I'm not sure I understand the issue. Can you please clarify? An image could help!

Do you perhaps mean:
* Detected corners are a little bit off, resulting in a 3d floorplan with edges a couple of decimals wrong?
* Want the (0,0,0) point to be center or a corner of the floorplan for better reference? 
* Want to change the height of certain walls? 
* Want to scale or round the size of the 3d floorplan so you can work in integers?
* Parts of the floorplan is not detected? Or imprecise?

Blender version [see how here](https://blender.stackexchange.com/questions/148129/what-version-have-i-installed), and "pip list" output could also be useful. 

If you clarify, I'll take a look at it tonight after work. 

Cheers,
@grebtsew

**Comment by grebtsew** [comment]
I see, I can change the floorplan position to 0,0,0. And see that the pivot point is a bit off. This happens because we are storeing positions relative to the image upper left corner. See images below.

![bild](https://user-images.githubusercontent.com/8101164/90309389-81390c80-dee8-11ea-9d64-ec3b94dc9037.png)
![bild](https://user-images.githubusercontent.com/8101164/90309446-06242600-dee9-11ea-947d-4b1a832dbfe9.png)

A solution would be to edit the `Blender/floorplan_to_3dObject_in_blender.py` file. Using the bpy library, find a way to set pivot points. How would you prefer the pivot points to be positioned? Center of objects or corners?

Cheers,
@grebtsew

**Comment by grebtsew** [comment]
Hi again @shaddeykatri !

Good news! I just solved the issue.

Now all created objects should have pivot points in approximated center of mesh. I also moved the floorplan to center of project.

I added functions to calculate center position of a verts matrix, then created each object from a zero location and moved each object to correct place instead of creating them with an offset. Which is how it should had been done from the beginning.

Please let me know if the solution solves this issue.

A small demonstration image:
![bild](https://user-images.githubusercontent.com/8101164/90323366-994c7280-df60-11ea-942c-9d6db92756ec.png)

Do let me know if you encounter any other problems with the project.

Cheers,
@grebtsew

**Comment by shaddeykatri** [comment]
Hi @grebtsew !

Thanks for properly understanding and solving the issue that too in such short amount of time.
This was exactly what i needed.
The pivot points of the individual objects and the floorplan are in the center.

Now I just have one question can we do doors and windows detection with just using opencv (i.e without the various machine learning object detection models)?

Cheers,
@shaddeykatri

**Comment by shaddeykatri** [comment]
Hi again @grebtsew !

After testing the code with some images for few minutes I noticed that the pivot of the parent floor plan object is still at origin 
![image](https://user-images.githubusercontent.com/31386786/90367180-17ef0000-e086-11ea-88b8-a58b29cfa49a.png)

Can we somehow change it to the center of the floorplan which will make the floor plan easier to navigate.

Thanks,
@shaddeykatri

**Comment by grebtsew** [comment]
Hi @shaddeykatri,

Yes, ofcourse that's an easy fix! Just pushed to master.

![bild](https://user-images.githubusercontent.com/8101164/90385854-fd1b8c00-e083-11ea-802b-266f2bb53d68.png)

Regarding Door and Window detection, I tried accomplishing this a couple of years ago. But had some issues differentiating between the two. I have started on another solution, however haven't really had time to implement it. My plan is to add it in the future. 

This is how far I've come.

Code for finding windows/doors/small rooms exist in "Development Center/FloorplanLibDemo/find_windows_and_doors.py" (also integrated into the ftbLibrary)
Result looks like this:
![bild](https://user-images.githubusercontent.com/8101164/90386947-926b5000-e085-11ea-920f-4595b6fa0201.png)

My plan is to use Orb Feature detection to determine what each box from the result above represent. (see ´Detections/Experimental/feature_matching_door.py´)
![bild](https://user-images.githubusercontent.com/8101164/90387083-d6f6eb80-e085-11ea-8b63-1d35a61c6c8a.png)

And then analyze the result with some additional conditions. 

I can't really say when this will be developed, but hopefully before the end of this year.
I am also working on a tutorial of how each core detection/function works in notebook jupyter.

Cheers,
@grebtsew
