### ISSUE TITLE
Blender path error 

### ISSUE THREAD

**Issue by iiskakov** [grebtsew/FloorplanToBlender3d#9]
**Describe the bug**
I am trying to run the latest version from   _doors-and-windows_ branch. The script fails when attempting to run blender. I suppose the problem is with default path. 
**Main branch works fine with same steps**. 

I also tried to use:

1. `/Applications/Blender.app/Contents/MacOS/Blender` since I am on Mac
2. `/usr/local/blender/blender` I thought for a second that since the script runs inside docker container, may be that it needs local path for docker installed blender.

Both didn't seem to work.

**To Reproduce**
1. `git clone --branch doors-and-windows https://github.com/grebtsew/FloorplanToBlender3d.git`
2. docker-compose run ftb
3. Press enter several times (all defaults)

**Expected behavior**
I expect this to create a floorplan.blend file with windows and doors

**Screenshots**
<img width="619" alt="image" src="https://user-images.githubusercontent.com/45936496/136698326-b42232a0-675f-40b1-a305-5b95b1c2fa64.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Version 10.15.7

**Comment by dogfootruler-kr** [comment]
Hey @iiskakov ,

If you use the docker-compose command then blender path should be `/usr/local/blender/blender` and there is also a small error in the `const.py` file, `TARGET_PATH` should be set to `"/Target/"` instead of `"./Target"`.

FYI: If you run it locally on MacOS the blender path should be `/Applications/Blender.app/Contents/MacOS/Blender`

Cheers

**Comment by grebtsew** [comment]
Hi,

This is now merged into Master/Main branch I will therefore close this issue.

Cheers,
@grebtsew
